### ISSUE TITLE
switchport configuration ignored if defined in multiple yml

### ISSUE THREAD

**Issue by cathode911** [arista-eosplus/ansible-eos-bridging#23]
In cases of using switchport configuration in different yml files, e.g

group_vars/leafs.yml
```
# Global leaf-only applied configuration
---
# Switchports configuration
switchports:
  - name: Ethernet1
    mode: trunk
    trunk_allowed_vlans:
      - 1300
      - 4009
      - 4010
      - 4011
  - name: Ethernet5
    mode: trunk
    trunk_allowed_vlans:
      - 1300
      - 4009
      - 4010
      - 4011
  - name: Ethernet7
    mode: trunk
    trunk_allowed_vlans:
      - 171
      - 4020
      - 4021
```
 
host_vars/10.2.200.68.yml
```
# Switchports configuration
switchports:
  - name: Ethernet2
    mode: access
    access_vlan: 4010
  - name: Ethernet6
    mode: access
    access_vlan: 4010
  - name: Ethernet10
    mode: access
    access_vlan: 4010
```

configuration in group_vars is _completely_ ignored - only configuration from host_vars is applied

TASK [arista.eos-bridging : Arista EOS switchport resources (Ansible >= 2.2)] **
ok: [10.2.200.68] => (item={u'access_vlan': 4010, u'name': u'Ethernet2', u'mode': u'access'})
ok: [10.2.200.69] => (item={u'access_vlan': 4011, u'name': u'Ethernet2', u'mode': u'access'})
ok: [10.2.200.68] => (item={u'access_vlan': 4010, u'name': u'Ethernet6', u'mode': u'access'})
ok: [10.2.200.69] => (item={u'access_vlan': 4011, u'name': u'Ethernet6', u'mode': u'access'})
ok: [10.2.200.69] => (item={u'access_vlan': 4011, u'name': u'Ethernet10', u'mode': u'access'})
ok: [10.2.200.68] => (item={u'access_vlan': 4010, u'name': u'Ethernet10', u'mode': u'access'})
 
It would be reasonable if port configuration in host config files would supersede global config thus allowing agile control over exclusions in port configuration.
